# Navigation Links
#   To link a page, specify the URL.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: PEOPLE
    url: people
    weight: 10
    matchRegexp: ^/people|^/authors
  - name: PUBLICATIONS
    url: publications
    weight: 11
  - name: TEACHING
    url: teaching
    weight: 12
    matchRegexp: ^/teaching|^/courses
  - name: EVENTS
    url: events
    weight: 13
    matchRegexp: ^/events|^/talk
  - name: JOIN
    url: join
    weight: 20
