# Navigation Links
#   To link a page, specify the URL.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: PEOPLE
    url: /Rycolab-new/people
    weight: 10
  - name: PUBLICATIONS
    url: /Rycolab-new/publications
    weight: 11
  - name: TEACHING
    url: /Rycolab-new/teaching
    weight: 12
  - name: EVENTS
    url: /Rycolab-new/events
    weight: 13
  - name: JOIN
    url: /Rycolab-new/join
    weight: 20
